# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: BiliRoamingX-PreBuilds

on:
  workflow_dispatch:
  repository_dispatch:
    types: [BiliRoamingX-PreBuilds]


jobs:
  Check-in:

    runs-on: ubuntu-latest

    steps:
    - name: Free Disk-Space
      run: df -h && sudo apt-get clean && docker system prune -a -f && sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc && df -h

    - name: Checkout
    - uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.13
        check-latest: true

    - name: "Set up requests"
      run: pip install requests

    - name: "run main.py"
      env:
        PAT: ${{secrets.PAT}}
      run: python main.py

    - name: "Set up Java"
      uses: actions/setup-java@main
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
        check-latest: true

    - name: "Run ReVanced CLI"
      run: java -jar /Downloads/revanced-cli.jar patch --merge /Downloads/integrations.apk --patch-bundle /Downloads/patches.jar --signing-levels 1,2,3 /Downloads/BiliBili.apk

    - name: "Upload artifact"
      uses: actions/upload-artifact@main
      with:
        name: ${{ inputs.Release_name }}
        path: /Downloads/

    - name: "Delete old workflow run using Personal Token"
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
